package apperror

const (
	CodeValidationError        = "validation_error"
	CodeEmailExists            = "email_already_exists"
	CodeInvalidCreds           = "invalid_credentials"
	CodeUnauthorized           = "unauthorized"
	CodeForbidden              = "forbidden"
	CodeUserNotFound           = "user_not_found"
	CodeInternal               = "internal_error"
	CodeInvalidRefresh         = "invalid_refresh_token"
	CodeCategoryNotFound       = "category_not_found"
	CodeProductNotFound        = "product_not_found"
	CodeFlavorNotFound         = "flavor_not_found"
	CodeStrengthNotFound       = "strength_not_found"
	CodeCartItemNotFound       = "cart_item_not_found"
	CodeInvalidStockOp         = "invalid_stock_operation"
	CodeInsufficientStock      = "insufficient_stock"
	CodeEmptyCart              = "empty_cart"
	CodeOrderNotFound          = "order_not_found"
	CodeInvalidOrderStatus     = "invalid_order_status"
	CodeMixNotFound            = "mix_not_found"
	CodeInvalidMixPercentTotal = "invalid_mix_percent_total"
	CodeInvalidMixItemProduct  = "invalid_mix_item_product"
	CodeTobaccoProductNotFound = "tobacco_product_not_found"
	CodeTagNotFound            = "tag_not_found"
	CodeDuplicateTagCode       = "duplicate_tag_code"
	CodeDuplicateTagName       = "duplicate_tag_name"
)
